version: '3.4'
x-xdebug-settings: &xdebug-settings
  XDEBUG_REMOTE_AUTOSTART: "On"
  XDEBUG_REMOTE_CONNECT_BACK: "Off"
  XDEBUG_REMOTE_HOST: "127.0.0.1"
  XDEBUG_PROFILER_ENABLE: "On"
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www/app/plugins/CommentActions
    environment:
      DATABASE_URL: mysql://kb:kb-secret@db/kanboard
      <<: *xdebug-settings
  pma:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    environment:
      PMA_HOST: db
      PMA_USER: kb
      PMA_PASSWORD: kb-secret
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kanboard
      MYSQL_USER: kb
      MYSQL_PASSWORD: kb-secret
  rights:
    image: busybox
    command: sh -c 'while true ; do chown -R $${USER_ID}.$${GROUP_ID} /target ; sleep 2s ; done'
    volumes:
      - .:/target
    environment:
      - USER_ID=10017
      - GROUP_ID=10003

